### ISSUE TITLE
Вопрос к статье: Внешний вид фокуса

### ISSUE THREAD

**Issue by AleksandrSl** [TatianaFokina/a11y-blog#3]
Есть небольшой вопрос по поводу обяхательности критериев. В кратком описании

> Когда элемент интерфейса получает фокус с клавиатуры, индикатор фокуса должен:
обводить элемент;
иметь соотношение контраста минимум 3:1 между одними и теми же пикселями в состоянии фокуса и без него;
иметь соотношение контраста минимум 3:1 по отношению к соседним цветам.
Область индикатора фокуса должна:
быть толщиной на 1 CSS-пиксель (дальше просто пиксель) больше минимальной области элемента или больше 4 пикселей, если индикатор равен самой короткой стороне элемента;
иметь соотношение контраста минимум 3:1 между одними и теми же пикселями в состоянии фокуса и без него;
иметь соотношение контраста минимум 3:1 по отношению к соседним цветам или быть толщиной 2 пикселя и больше.

и потом дальше в списке критериев

> в первую очередь со сплошным начертанием;
полностью обводит или окаймляет элемент;
...

все критерии звучат как обязательные к выполнению одновременно.

При этом дальше в примерах есть, например, кнопка с пунктирной обводкой, что явно не соответсвует сплошному начертанию.

В спецификации над двумя группами критериев для индикатора и области индикатора написано
> one or both of the following are true.

И в таком случае пунктирная обводка имеет право на жизнь, если соответсвует хотя бы второй группе критериев, которые рассчитаны на область индикатора.

Вообще выглядит так, что критерии контрастности одни и те же, а дальше есть вариант либо обводка может быть какой угодно толщины, но при этом сплошной. Либо какой угодно по "начертанию", но иметь определенную площадь.

Если я правильно понял спецификацию, могу попробовать обновить текст

**Comment by TatianaFokina** [comment]
Тут интересно. В самом критерии указано, что "The entire focus indicator meets all the following: encloses the user interface component or sub-component". Если посмотреть на то, что в этом контексте означает "encloses", то "solidly bounds or surrounds". "Solidly bounds" — это когда "the focus indicator bullets states that the focus indicator "encloses" the user interface component".

Пунктирная линия с точки зрения терминологии "the dashed outline does not `solidly bound`". То есть, это будто бы больше исключение, чем правило. Как в случае с изменением фона элемента при фокусе. Так тоже можно делать, но с припиской, что не в первую очередь. Я указала, что пунктирную линию можно использовать в объяснении своими словами, на самом деле. Но в кратком объяснении критерия и правда не написано ничего про пунктирную линию.

**Comment by TatianaFokina** [comment]
Вот такую [пометку сделала и ещё немного других исправлений](https://github.com/TatianaFokina/a11y-blog/commit/5ac155a36b4c55b982e114c7e64856ca19e2a0ed). Теперь стал очевиднее этот момент?

**Comment by AleksandrSl** [comment]
Стало понятнее, но мне все еще кажется, что вариант или solid или не solid но толстый соответствует спеке, и более понятен.
Например, как написали [тут](https://hidde.blog/focus-appearance-too-complex/).
> the focus indicator needs to either be a solid line (so not dotted or dashed), or have a certain level or thickness (in which it can be dotted or dashed

**Comment by TatianaFokina** [comment]
В разделе коротко стараюсь пересказывать точно то, как написано в нормативной части спеки. Кажется мне, что лучше туда не добавлять много от себя.

Мартин Андерхилл, например, `[прямо написал](https://www.tempertemper.net/blog/focus-appearance-explained)`, что только solid line приветствуется. И всё это следствия того, что уж очень сложно критерий устроен. Может они как-то подтюнят его, а то и правда странно что в нормативной части пишут про сплошную линию, а потом несплошную.

**Comment by AleksandrSl** [comment]
Но в нормативной же части указано в самом начале
> When the keyboard [focus indicator](https://www.w3.org/TR/WCAG22/#dfn-focus-indicator) is visible, one or both of the following are true:

> one or both of the following are true:

То есть применяется хотя бы один из двух, и поэтому 
> the focus indicator needs to either be a solid line (so not dotted or dashed), or have a certain level or thickness (in which it can be dotted or dashed
Для меня звучит достаточно точным изложением 

Я думаю, нам пора привлечь кого-то третьего :smile_cat:

**Comment by TatianaFokina** [comment]
Добавила вот такое уточнение — 0f49893.
