### ISSUE TITLE
Опечатка в статье: Внешний вид фокуса

### ISSUE THREAD

**Issue by yhdgms1** [TatianaFokina/a11y-blog#4]
> Представим, что у кнопки радиус 100 пикселей. В этом случае умножаем 3.14 на 2 и затем на 100. Получаем `314` пикселей. В этом случае внешняя рамка может быть шириной 1 пиксель, так как эта область получается больше минимальной. А вот рамка внутри круглой кнопки уже должна быть минимум 2 пикселя.

При 3.14 * 2 * 100 должно получиться 628. Наверное, забыли умножить на 2.
Но, может, я неправильно понял что на что умножается, поэтому вместо PR - Issue.

**Comment by TatianaFokina** [comment]
Привет! Это я демонстрирую потрясающие навыки в математике 😅 [Исправила вычисления](https://github.com/TatianaFokina/a11y-blog/commit/86a9f18b8fe8b83a8d186595e93cf9773c55e47a) и выбрала ещё радиус поменьше.

Спасибо!
