### ISSUE TITLE
Что-то не то с текстом

### ISSUE THREAD

**Issue by alexnozer** [TatianaFokina/a11y-blog#9]
Мне кажется, что что-то не так с [этим](https://github.com/TatianaFokina/a11y-blog/blob/b2bddd208ce11d29bfdd52e9a42e80f9f8b739c3/src/ru/articles/is-sepia-mode-essential/index.md?plain=1#L104) фрагментом текста:

> Сепия на фоне текста Режим сепии делает читать длинные тексты.

То ли знаков препинания не хватает, то ли со склонением что-то не то.

**Comment by TatianaFokina** [comment]
Привет, да не то слово! Я поправила всё, заодно вычитала ещё раз. Что-то тяжеловато мне далось писать один и тот же текст на двух языках одновременно.
